name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        env:
          CI: true
          SF_Username:        ${{ secrets.SF_Username }}
          SF_Password:        ${{ secrets.SF_Password }}
          SF_Url:             ${{ secrets.SF_Url }}
          Api_Username:       ${{ secrets.Api_Username }}
          Api_Password:       ${{ secrets.Api_Password }}
          Api_Client_Id:      ${{ secrets.Api_Client_Id }}
          Api_Client_Secret:  ${{ secrets.Api_Client_Secret }}
          Admin_Username:     ${{ secrets.Admin_Username }}
          Admin_Password:     ${{ secrets.Admin_Password }}
        run: npx playwright test --grep "@api" --reporter=html,allure-playwright
        continue-on-error: true   # ensures report steps run even if tests fail


      - name: Debug env vars
        run: |
          echo "Client ID exists: ${{ secrets.Api_Client_Id != '' }}"
          echo "Client Secret exists: ${{ secrets.Api_Client_Secret != '' }}"
          echo "Username exists: ${{ secrets.Api_Username != '' }}"
        env:
          Api_Client_Id: ${{ secrets.Api_Client_Id }}
          Api_Client_Secret: ${{ secrets.Api_Client_Secret }}
          Api_Username: ${{ secrets.Api_Username }}

      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Upload Test Results (traces, screenshots, videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages